### ISSUE TITLE
Internal ELB variable misnamed

### ISSUE THREAD

**Issue by roooms** [iainthegray/terraform-aws-vault#4]
As `var.internal_elb` is a switch I think it should be renamed `var.use_internal_elb` to match the other switch names all starting with `use_`. I was going to PR this but it's in a few places (and examples) and I didn't have the chance to run tests so I'm raising as an issue.

**Comment by iainthegray** [comment]
actually the code is correct — there are 2 elb variables.
1. use_elb which dictates whether the elb is used at all and
2. internal_elb which dictates whether the elb will be internal or not
so if you have use_elb it will use one, and you can then decide if it is internal or external based on teh internal_elb variable
not hugely elegant I admit
